debug: true
logging:
  level:
    root: INFO
    com:
      ubiqube:
        juju: DEBUG

server:
  error:
    include-binding-errors: always
    whitelabel:
      enabled: false
  port: 8200
  servlet:
    contextPath: /juju

#springdoc:
#  api-docs:
#    path: /api-docs
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

#spring:
#  security:
#    oauth2:
#      resourceserver:
#       jwt:
#          issuer-uri: http://mano-auth:8080/auth/realms/mano-realm