#debug: true
logging:
  level:
    root: INFO
    com:
      ubiqube:
        juju: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  elastic:
    metrics:
      export:
        host: http://mano-es:9200
        index: mano-metrics-juju
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0

mano:  
  config:
    type: juju

server:
  error:
    include-binding-errors: always
    whitelabel:
      enabled: false
  port: 8200
  servlet:
    contextPath: /juju

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  output:
    ansi:
      enabled: always

springdoc:
  enable-data-rest: false
