#debug: true
logging:
  level:
    root: INFO
    com:
      ubiqube:
        juju: DEBUG

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  elastic:
    metrics:
      export:
        host: http://mano-es:9200
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0

mano:  
  config:
    type: vnfm

server:
  error:
    include-binding-errors: always
    whitelabel:
      enabled: false
  port: 8200
  servlet:
    contextPath: /juju

